apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-test-default
spec:
  replicas: 6
  selector:
    matchLabels:
      app: scheduler-test
  template:
    metadata:
      labels:
        app: scheduler-test
    spec:
      tolerations:
      - key: nodepool/scale
        value: static
        effect: NoSchedule
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 1000m
            memory: 1Gi
      nodeSelector:
        kubernetes.azure.com/agentpool: linux2