apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-test-default
spec:
  replicas: 6
  selector:
    matchLabels:
      app: scheduler-test-default
  template:
    metadata:
      labels:
        app: scheduler-test-default
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
      nodeSelector:
        kubernetes.azure.com/agentpool: linux